name: Build and Predeploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (equivalent to 'checkout_self.yaml')
      - name: Checkout code
        uses: actions/checkout@v3

      # Run bash script to create variables directory
      - name: Create variables directory
        run: |
          set -euxo pipefail
          mkdir -p ${{ github.workspace }}/cicd/variables

      # Upload the artifact (equivalent to 'PublishPipelineArtifact@1')
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-artifact
          path: ${{ github.workspace }}/cicd/variables

  predeploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the predeploy job runs after the build job

    steps:
      # Download the artifact that was uploaded in the build job
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-artifact

      # (Optional) Do something with the downloaded artifact
      - name: List contents of artifact
        run: |
          ls -la ${{ github.workspace }}

      # Run the Python script to retrieve the ADO PAT Token
      - name: Retrieve ADO PAT Token
        id: ado_token
        run: |
          python3 load_user_vars.py
        working-directory: ${{ github.workspace }}/scripts/python

      # (Optional) Further steps can be added here, using the ADO token if needed
