name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (equivalent to 'checkout_self.yaml')
      - name: Checkout code
        uses: actions/checkout@v3

      # Run bash script to create variables directory
      - name: Create variables directory
        run: |
          set -euxo pipefail
          mkdir -p ${{ github.workspace }}/cicd/variables

      # Upload the artifact (equivalent to 'PublishPipelineArtifact@1')
      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-artifact
          path: ${{ github.workspace }}/cicd/variables
