name: CI/CD Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Variables Directory
        run: |
          mkdir -p ${{ github.workspace }}/${{ github.event.inputs.framework.module.inputs.workingDirectory || 'cicd/variables' }}
        shell: bash

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.framework.module.name || 'default-artifact-name' }}  # Ensure the artifact name is not empty
          path: ${{ github.workspace }}/${{ github.event.inputs.framework.module.inputs.workingDirectory || 'cicd/variables' }}

      - name: Install Python Dependencies
        run: |
          python -m pip install pyyaml

      - name: Load User Variables
        run: |
          python ${{ github.workspace }}/scripts/load_user_vars.py "${{ github.workspace }}/${{ github.event.inputs.framework.module.inputs.workingDirectory || 'cicd/variables' }}" '{"environment": "${{ github.event.inputs.framework.environment.name }}", "project": "${{ github.repository }}"}'
